#!/bin/bash
set -eu
SCRIPT_PATH="$(cd -- "$(dirname "$0")" >/dev/null 2>&1; pwd -P)"
export PATH="$SCRIPT_PATH/.node/bin:$PATH"
export PLAYWRIGHT_BROWSERS_PATH="${SCRIPT_PATH}/node_modules/playwright-core/.local-browsers"
exec npx playwright "$@"